[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = [
    "RUSTSEC-2021-0139", # ansi_term is unmaintained, but no issues found until now
]

[licenses]
version = 2
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
    "Zlib",
]

[licenses.private]
ignore = true

[sources]
unknown-git = "deny"

allow-git = [
    "https://github.com/myOmikron/galvyn.git",
]