[Migration]
Hash = "9640871407894581327"
Initial = true
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "Club"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/club/db.rs"
Line = 16
Column = 9

[[Migration.Operations.Fields]]
Name = "name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/club/db.rs"
Line = 17
Column = 9

[[Migration.Operations.Fields]]
Name = "modified_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_update_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/club/db.rs"
Line = 20
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/club/db.rs"
Line = 22
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "Domain"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/domain/db.rs"
Line = 12
Column = 9

[[Migration.Operations.Fields]]
Name = "domain"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/domain/db.rs"
Line = 14
Column = 9

[[Migration.Operations.Fields]]
Name = "is_primary"
Type = "boolean"

[[Migration.Operations.Fields.Annotations]]
Type = "default_value"
Value = "false"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/domain/db.rs"
Line = 17
Column = 9

[[Migration.Operations.Fields]]
Name = "mailboxes_left"
Type = "int64"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/domain/db.rs"
Line = 19
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "ClubMember"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/role/db.rs"
Line = 12
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "ClubAdmin"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/role/db.rs"
Line = 23
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "SuperAdmin"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/role/db.rs"
Line = 34
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "invitemodel"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 12
Column = 9

[[Migration.Operations.Fields]]
Name = "username"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 15
Column = 9

[[Migration.Operations.Fields]]
Name = "display_name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 16
Column = 9

[[Migration.Operations.Fields]]
Name = "expires_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 18
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 21
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "InvitedClubMember"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 37
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "InvitedClubAdmin"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 48
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "InvitedSuperAdmin"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 59
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "OidcProvider"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 13
Column = 9

[[Migration.Operations.Fields]]
Name = "name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 14
Column = 9

[[Migration.Operations.Fields]]
Name = "client_secret"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 64

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 15
Column = 9

[[Migration.Operations.Fields]]
Name = "redirect_uri"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 16
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "OidcAuthenticationToken"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 23
Column = 9

[[Migration.Operations.Fields]]
Name = "redirect_url"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 26
Column = 9

[[Migration.Operations.Fields]]
Name = "code"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 64

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 28
Column = 9

[[Migration.Operations.Fields]]
Name = "expires_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 29
Column = 9

[[Migration.Operations.Fields]]
Name = "nonce"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 32
Column = 9

[[Migration.Operations.Fields]]
Name = "scopes"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 33
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "Account"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 10
Column = 9

[[Migration.Operations.Fields]]
Name = "username"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "unique"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 14
Column = 9

[[Migration.Operations.Fields]]
Name = "display_name"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 16
Column = 9

[[Migration.Operations.Fields]]
Name = "hashed_password"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 18
Column = 9

[[Migration.Operations.Fields]]
Name = "modified_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_update_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 21
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 23
Column = 9

[[Migration.Operations]]
Type = "CreateModel"
Name = "galvynsession"

[[Migration.Operations.Fields]]
Name = "id"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/git/checkouts/galvyn-f52542b4eef301aa/5a18a61/galvyn-core/src/session.rs"
Line = 40
Column = 5

[[Migration.Operations.Fields]]
Name = "expires_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/git/checkouts/galvyn-f52542b4eef301aa/5a18a61/galvyn-core/src/session.rs"
Line = 41
Column = 5

[[Migration.Operations.Fields]]
Name = "data"
Type = "binary"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "/usr/local/cargo/git/checkouts/galvyn-f52542b4eef301aa/5a18a61/galvyn-core/src/session.rs"
Line = 42
Column = 5

[[Migration.Operations]]
Type = "CreateField"
Model = "OidcAuthenticationToken"

[Migration.Operations.Field]
Name = "provider"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "OidcProvider"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 25
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "OidcAuthenticationToken"

[Migration.Operations.Field]
Name = "account"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Account"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/oidc_provider/db.rs"
Line = 31
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "InvitedClubAdmin"

[Migration.Operations.Field]
Name = "invite"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "invitemodel"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 50
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "InvitedClubAdmin"

[Migration.Operations.Field]
Name = "club"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Club"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 52
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "InvitedClubMember"

[Migration.Operations.Field]
Name = "invite"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "invitemodel"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 39
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "InvitedClubMember"

[Migration.Operations.Field]
Name = "club"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Club"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 41
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "InvitedSuperAdmin"

[Migration.Operations.Field]
Name = "invite"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "invitemodel"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/invite/db.rs"
Line = 61
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "SuperAdmin"

[Migration.Operations.Field]
Name = "account"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Account"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/role/db.rs"
Line = 36
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "ClubAdmin"

[Migration.Operations.Field]
Name = "account"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Account"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/role/db.rs"
Line = 25
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "ClubAdmin"

[Migration.Operations.Field]
Name = "club"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Club"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/role/db.rs"
Line = 27
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "Domain"

[Migration.Operations.Field]
Name = "club"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Club"
ColumnName = "uuid"
OnDelete = "Restrict"
OnUpdate = "Restrict"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/domain/db.rs"
Line = 15
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "ClubMember"

[Migration.Operations.Field]
Name = "account"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Account"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/role/db.rs"
Line = 14
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "ClubMember"

[Migration.Operations.Field]
Name = "club"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Club"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/role/db.rs"
Line = 16
Column = 9
