[Migration]
Hash = "6786120617686982430"
Initial = false
Dependency = 1
Replaces = []

[[Migration.Operations]]
Type = "CreateField"
Model = "website"

[Migration.Operations.Field]
Name = "last_deployment"
Type = "datetime"
Annotations = []
