[Migration]
Hash = "10466622366875789945"
Initial = false
Dependency = 1
Replaces = []

[[Migration.Operations]]
Type = "CreateModel"
Name = "MailAlias"

[[Migration.Operations.Fields]]
Name = "uuid"
Type = "uuid"

[[Migration.Operations.Fields.Annotations]]
Type = "primary_key"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/mail_alias/db.rs"
Line = 14
Column = 9

[[Migration.Operations.Fields]]
Name = "local_part"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 255

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/mail_alias/db.rs"
Line = 15
Column = 9

[[Migration.Operations.Fields]]
Name = "status"
Type = "varchar"

[[Migration.Operations.Fields.Annotations]]
Type = "max_length"
Value = 32

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/mail_alias/db.rs"
Line = 21
Column = 9

[[Migration.Operations.Fields]]
Name = "mailcow_id"
Type = "int64"
Annotations = []

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/mail_alias/db.rs"
Line = 23
Column = 9

[[Migration.Operations.Fields]]
Name = "created_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/mail_alias/db.rs"
Line = 25
Column = 9

[[Migration.Operations.Fields]]
Name = "modified_at"
Type = "datetime"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_create_time"

[[Migration.Operations.Fields.Annotations]]
Type = "auto_update_time"

[[Migration.Operations.Fields.Annotations]]
Type = "not_null"

[Migration.Operations.Fields.SourceDefinedAt]
File = "webserver/src/models/mail_alias/db.rs"
Line = 27
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "MailAlias"

[Migration.Operations.Field]
Name = "domain"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "Domain"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/mail_alias/db.rs"
Line = 17
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "MailAlias"

[Migration.Operations.Field]
Name = "account"
Type = "uuid"

[[Migration.Operations.Field.Annotations]]
Type = "foreign_key"

[Migration.Operations.Field.Annotations.Value]
TableName = "ClubAccount"
ColumnName = "uuid"
OnDelete = "Cascade"
OnUpdate = "Cascade"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/mail_alias/db.rs"
Line = 19
Column = 9
