[Migration]
Hash = "4995908946571615720"
Initial = false
Dependency = 2
Replaces = []

[[Migration.Operations]]
Type = "CreateField"
Model = "Club"

[Migration.Operations.Field]
Name = "use_xauth"
Type = "boolean"

[[Migration.Operations.Field.Annotations]]
Type = "default_value"
Value = "false"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/club/db.rs"
Line = 23
Column = 9

[[Migration.Operations]]
Type = "CreateField"
Model = "ClubAccount"

[Migration.Operations.Field]
Name = "has_app_password"
Type = "boolean"

[[Migration.Operations.Field.Annotations]]
Type = "default_value"
Value = "false"

[[Migration.Operations.Field.Annotations]]
Type = "not_null"

[Migration.Operations.Field.SourceDefinedAt]
File = "webserver/src/models/account/db.rs"
Line = 62
Column = 9
