name: Build & Tests on linux
on:
  push:
    paths-ignore:
      - "**/*.md"
  pull_request:

jobs:
  build_ts:
    name: Build typescript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        working-directory: frontend
        run: |
          npm install
          npm run build
  build_rs:
    name: Build & Tests on linux
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v3

      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - name: Install dependencies
        run: |
          rustup component add clippy
          cargo install clippy-sarif sarif-fmt cargo-deny

      - name: Build bnv-manager-v2
        run: cargo build -p bnv-manager-v2

      - name: Run cargo-deny
        run: cargo deny check --hide-inclusion-graph

      - name: Run rust-clippy
        run: cargo clippy --workspace --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload clippy analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true