name: Renovate
on:
  workflow_dispatch:
  schedule:
    # The "*" (#42, asterisk) character has special semantics in YAML, so this
    # string has to be quoted.
    - cron: '0/15 * * * *'
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.8
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_GIT_PRIVATE_KEY: ${{ secrets.RENOVATE_GPG_KEY }}
          DHI_REGISTRY_USER: ${{ secrets.DHI_REGISTRY_USER }}
          DHI_REGISTRY_PASSWORD: ${{ secrets.DHI_REGISTRY_PASSWORD }}

